### PR TITLE
Dropdown to filter all/full/restricted users.

### PR DESCRIPTION
**Pull request by DavidBoike**
We use team time zone at [Particular Software](https://github.com/Particular) and we love it! But we recently added a group of single-channel guests to our Slack team and we'd love to be able to filter for just the full users, or just the restricted users.

I've done quite a bit of Angular but this is my first attempt with Ember so I apologize in advance for all the conventions and best practices I've no doubt trampled upon. Please let me know what I can fix up!

### CODE REVIEW

**Comment by alisdair** [comment]
Hey, thanks for the patch! It looks like a useful addition.

The only things I'd request before merge are:

- Can you fix the ESLint errors? I don't want to merge a red build. You can run the tests locally at http://localhost:4200/tests or with `ember test`
- Also, in the controller, the `actions` block should go at the end of the module, i.e. after `filteredUsers`

**Comment by DavidBoike** [comment]
@alisdair fixed both, but for some reason unknown to me, the Travis build keeps hanging (tried twice) during `ember test`. Any idea what that could be?

**Comment by alisdair** [comment]
No idea. But tests pass locally and I don't think the Travis failure is anything to do with this branch, so merging.

Thanks again!

**Comment by alisdair** [comment]
@DavidBoike Now released & deployed in 1.2.0: https://teamtime.zone

(Still don't know what's up with Travis.)

**Comment by hmemcpy** [comment]
Awesome, thanks @DavidBoike and @alisdair!
Looks a bit cut off in my Chrome on Windows, though...

image

**Pull request merged**
